nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  yogaplay:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN}"
npmAuthToken: "${NPM_TOKEN}"
