nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  yogaplay:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN}"
npmAuthToken: "${NPM_TOKEN}"
