name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build
        run: yarn run build:lib
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish
        run: yarn npm publish --no-private
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
